# Objetivo: Deixar o dado impecável para os próximos notebooks.

#### Configurações Iniciais (Imports de pandas, numpy, etc).

In [13]:
import pandas as pd
import numpy as np

#### Carregamento dos Dados.

In [14]:
df = pd.read_csv('../data/raw/train.csv')

#### Limpeza de Strings (Remoção de espaços ' ' com strip()).

In [15]:
df['ID'] = df['ID'].str.strip()                                
df['Delivery_person_ID'] = df['Delivery_person_ID'].str.strip()  
df['Delivery_person_Age'] = df['Delivery_person_Age'].str.strip()               
df['Delivery_person_Ratings'] = df['Delivery_person_Ratings'].str.strip()           
df['Order_Date'] = df['Order_Date'].str.strip()                        
df['Time_Orderd'] = df['Time_Orderd'].str.strip()                       
df['Time_Order_picked'] = df['Time_Order_picked'].str.strip()                 
df['Weatherconditions'] = df['Weatherconditions'].str.strip()                 
df['Road_traffic_density'] = df['Road_traffic_density'].str.strip()              
df['Type_of_order'] = df['Type_of_order'].str.strip()                     
df['Type_of_vehicle'] = df['Type_of_vehicle'].str.strip()                   
df['multiple_deliveries'] = df['multiple_deliveries'].str.strip()               
df['Festival'] = df['Festival'].str.strip()                          
df['City'] = df['City'].str.strip()                              
df['Time_taken(min)'] = df['Time_taken(min)'].str.strip()

#### Tratamento de Dados da coluna 'Time_taken(min)' (Lidar string que contém informação numérica).

In [16]:
df['Time_taken(min)'] = df['Time_taken(min)'].str.extract('(\d+)')

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\lucas\AppData\Local\Temp\ipykernel_26160\3301419101.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['Time_taken(min)'] = df['Time_taken(min)'].str.extract('(\d+)')

#### Tratamento de Dados da coluna 'Weatherconditions' (Lidar informação repetitiva).

In [17]:
df['Weatherconditions'] = df['Weatherconditions'].str.slice(start=11)

#### Conversão de Tipos (Datas para datetime, números para int/float).

In [18]:
df['ID'] = df['ID'].astype(str) 
df['Delivery_person_ID'] = df['Delivery_person_ID'].astype(str)    
df['Delivery_person_Age'] = pd.to_numeric(df['Delivery_person_Age'], errors='coerce')    
df['Delivery_person_Ratings'] = pd.to_numeric(df['Delivery_person_Ratings'], errors='coerce')    
df['Restaurant_latitude'] = pd.to_numeric(df['Restaurant_latitude'], errors='coerce')
df['Restaurant_longitude'] = pd.to_numeric(df['Restaurant_longitude'], errors='coerce')
df['Delivery_location_latitude'] = pd.to_numeric(df['Delivery_location_latitude'], errors='coerce')
df['Delivery_location_longitude'] = pd.to_numeric(df['Delivery_location_longitude'], errors='coerce')
df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='%d-%m-%Y')
df['Time_Orderd'] = pd.to_datetime(df['Time_Orderd'], format='%H:%M:%S', errors='coerce').dt.strftime('%H:%M:%S') 
df['Time_Order_picked'] = pd.to_datetime(df['Time_Order_picked'], format='%H:%M:%S', errors='coerce').dt.strftime('%H:%M:%S') 
df['Weatherconditions'] = df['Weatherconditions'].astype(str)    
df['Road_traffic_density'] = df['Road_traffic_density'].astype(str)    
df['Vehicle_condition'] = pd.to_numeric(df['Vehicle_condition'], errors='coerce')
df['Type_of_order'] = df['Type_of_order'].astype(str)    
df['Type_of_vehicle'] = df['Type_of_vehicle'].astype(str)    
df['multiple_deliveries'] = pd.to_numeric(df['multiple_deliveries'], errors='coerce')    
df['Festival'] = df['Festival'].astype(str)    
df['City'] = df['City'].astype(str)
df['Time_taken(min)'] = pd.to_numeric(df['Time_taken(min)'], errors='coerce')

#### Tratamento de Dados Ausentes (Lidar com o texto 'NaN ').

In [19]:
df.replace('NaN', np.nan, inplace=True)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,11:30:00,11:45:00,Sunny,High,2.0,Snack,motorcycle,0.0,No,Urban,24.0
1,0xb379,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,19:45:00,19:50:00,Stormy,Jam,2.0,Snack,scooter,1.0,No,Metropolitian,33.0
2,0x5d6d,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,08:30:00,08:45:00,Sandstorms,Low,0.0,Drinks,motorcycle,1.0,No,Urban,26.0
3,0x7a6a,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,18:00:00,18:10:00,Sunny,Medium,0.0,Buffet,motorcycle,1.0,No,Metropolitian,21.0
4,0x70a2,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,13:30:00,13:45:00,Cloudy,High,1.0,Snack,scooter,1.0,No,Metropolitian,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7750,0xccee,AGRRES010DEL01,21.0,4.7,27.163303,78.057044,27.273303,78.167044,2022-02-16,22:55:00,23:10:00,Cloudy,Low,0.0,Drinks,motorcycle,0.0,No,Metropolitian,22.0
7751,0x22d0,SURRES01DEL01,37.0,4.8,21.186438,72.794115,21.226438,72.834115,2022-03-11,13:30:00,13:35:00,Windy,High,0.0,Meal,motorcycle,1.0,No,Metropolitian,38.0
7752,0xd45,JAPRES02DEL03,NaN,NaN,26.914142,75.805704,27.004142,75.895704,2022-03-20,NaN,17:50:00,NaN,NaN,3.0,Snack,electric_scooter,1.0,No,Urban,32.0
7753,0xbc0f,MUMRES18DEL03,20.0,4.6,19.109300,72.825451,19.169300,72.885451,2022-03-15,20:50:00,20:55:00,Stormy,Jam,1.0,Snack,motorcycle,0.0,No,Metropolitian,28.0
7754,0x3da7,PUNERES010DEL01,32.0,5.0,18.539299,73.897902,18.609299,73.967902,2022-03-29,17:35:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Padronização de nomes de colunas (Snake Case e sem caracteres especiais)

In [20]:
df.columns = [col.lower().strip().replace('(', '').replace(')', '').replace(' ', '_') for col in df.columns]

#### Descobrindo se o restaurante e o local da entrega estão na Índia

In [21]:
# 1. Definindo as constantes dos limites da Índia
LAT_LIMITS = (8.0, 38.0)
LON_LIMITS = (68.0, 98.0)

# 2. Criando a coluna de validação para a entrega (Delivery)
df['is_india_delivery'] = (
    df['delivery_location_latitude'].between(LAT_LIMITS[0], LAT_LIMITS[1]) & 
    df['delivery_location_longitude'].between(LON_LIMITS[0], LON_LIMITS[1])
)

# 3. Criando a coluna de validação para o restaurante (Restaurant)
df['is_india_restaurant'] = (
    df['restaurant_latitude'].between(LAT_LIMITS[0], LAT_LIMITS[1]) & 
    df['restaurant_longitude'].between(LON_LIMITS[0], LON_LIMITS[1])
)

# 4. Verificando quantos registros estão fora da Índia em cada caso
print("Validação de Localização (Índia):")
print(f"Entregas na Índia: \n{df['is_india_delivery'].value_counts()}\n")
print(f"Restaurantes na Índia: \n{df['is_india_restaurant'].value_counts()}")

Validação de Localização (Índia):
Entregas na Índia:
is_india_delivery
True     7125
False     630
Name: count, dtype: int64

Restaurantes na Índia:
is_india_restaurant
True     7039
False     716
Name: count, dtype: int64

#### Visualização completa dos dados antes da exportação

In [22]:
display(df)

,id,delivery_person_id,delivery_person_age,delivery_person_ratings,restaurant_latitude,restaurant_longitude,delivery_location_latitude,delivery_location_longitude,order_date,time_orderd,...,road_traffic_density,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city,time_takenmin,is_india_delivery,is_india_restaurant
0,0x4607,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,11:30:00,...,High,2.0,Snack,motorcycle,0.0,No,Urban,24.0,True,True
1,0xb379,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,19:45:00,...,Jam,2.0,Snack,scooter,1.0,No,Metropolitian,33.0,True,True
2,0x5d6d,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,08:30:00,...,Low,0.0,Drinks,motorcycle,1.0,No,Urban,26.0,True,True
3,0x7a6a,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,18:00:00,...,Medium,0.0,Buffet,motorcycle,1.0,No,Metropolitian,21.0,True,True
4,0x70a2,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,13:30:00,...,High,1.0,Snack,scooter,1.0,No,Metropolitian,30.0,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7750,0xccee,AGRRES010DEL01,21.0,4.7,27.163303,78.057044,27.273303,78.167044,2022-02-16,22:55:00,...,Low,0.0,Drinks,motorcycle,0.0,No,Metropolitian,22.0,True,True
7751,0x22d0,SURRES01DEL01,37.0,4.8,21.186438,72.794115,21.226438,72.834115,2022-03-11,13:30:00,...,High,0.0,Meal,motorcycle,1.0,No,Metropolitian,38.0,True,True
7752,0xd45,JAPRES02DEL03,NaN,NaN,26.914142,75.805704,27.004142,75.895704,2022-03-20,NaN,...,NaN,3.0,Snack,electric_scooter,1.0,No,Urban,32.0,True,True
7753,0xbc0f,MUMRES18DEL03,20.0,4.6,19.109300,72.825451,19.169300,72.885451,2022-03-15,20:50:00,...,Jam,1.0,Snack,motorcycle,0.0,No,Metropolitian,28.0,True,True
7754,0x3da7,PUNERES010DEL01,32.0,5.0,18.539299,73.897902,18.609299,73.967902,2022-03-29,17:35:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True

#### Exportação (Salvar como train_cleaned.csv).

In [23]:
df.to_csv('../data/processed/train_clean.csv', index=False)